name: "AWS Copilot"
description: "AWS Copilot GitHub Action"
author: "ekojsalim"
inputs:
  command:
    required: true
    description: "The copilot command to run"
    default: "install"
  app:
    required: false
    description: "Application name"
  env:
    required: false
    description: "Environment name"
  name:
    required: false
    description: "Service name"
  tag:
    required: false
    description: "ECR tag name"
  resource-tags:
    required: false
    description: "Resource tags, comma-separated key-value pairs"
  path:
    required: false
    description: "Path to the working directory"
  github-token:
    required: false
    description: "GitHub token used to fetch latest copilot release. You must specify this or the version input."
  version:
    required: false
    description: "Copilot version to install. You must specify this or the github-token input."
  force:
    required: false
    default: "false"
    description: "Use the --force flag"
  detach:
    required: false
    default: "true"
    description: "Whether to run the copilot deploy command in detached mode"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  color: blue
  icon: box
